services:
  user_service:
    build: ./UserService
    volumes:
      - ./UserService:/app
    command: ["npm", "start"]
    ports:
      - "3000:3000"


  admission_service:
    build: 
      context: .
      dockerfile: ./AdmissionService/Dockerfile
    volumes:
      - ./AdmissionService:/app
    command: ["npm", "start"]
    ports:
      - "3001:3001"


  # enrollment_service:
  #   build: ./EnrollmentService
  #   volumes:
  #     - ./EnrollmentService:/app
  #   command: ["npm", "start"]

