services:
  user_service:
    build: ./UserService
    volumes:
      - ./UserService:/app
    command: ["npm", "start"]
    ports:
      - "3000:3000"

  admission_service:
    build: ./AdmissionService
    volumes:
      - ./AdmissionService:/app
    command: ["npm", "start"]
    ports:
      - "3001:3001"

  advice_Service:
    build: ./AdviceService
    volumes:
      - ./AdviceService:/app
    command: ["npm", "start"]
    ports:
      - "3003:3003"
  enrollment_service:
    build: ./EnrollmentService
    volumes:
      - ./EnrollmentService:/app
    command: ["npm", "start"]
    ports:
      - "3002:3002"

