version: '3'
services:
  user_service:
    build: ./UserService
    volumes:
      - ./UserService:/app
    command: ["npm", "start"]
    ports:
      - "3000:3000"
    networks:
      - microservices

  admission_service:
    build: ./AdmissionService
    volumes:
      - ./AdmissionService:/app
    command: ["npm", "start"]
    ports:
      - "3001:3001"
    networks:
      - microservices

  advice_service:
    build: ./AdviceService
    volumes:
      - ./AdviceService:/app
    command: ["npm", "start"]
    ports:
      - "3003:3003"
    networks:
      - microservices

  enrollment_service:
    build: ./EnrollmentService
    volumes:
      - ./EnrollmentService:/app
    command: ["npm", "start"]
    ports:
      - "3002:3002"
    networks:
      - microservices

networks:
  microservices:
